### PR TITLE
Change from deprecated flask.ext.* to flask_*

### PR DESCRIPTION
**Pull request by jeffwidman**
flask.ext.\* is deprecated, see: https://github.com/mitsuhiko/flask/issues/1135

### CODE REVIEW

**Comment by cburmeister** [comment]
This isn't working with `Flask-Bcrypt`:
```
>>> from flask_bcrypt import Bcrypt
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named flask_bcrypt
```

**Comment by jeffwidman** [comment]
Weird, as I've never encountered an extension that didn't work with the new syntax. I'm not familiar enough with Flask extension internals to understand the root cause, but I suspect Flask-Bcrypt needs updating.

**Comment by jeffwidman** [comment]
With Flask 0.11 out, it'll throw warnings when importing `flask.ext.*`

**Comment by jeffwidman** [comment]
Is this repo abandoned?

**Comment by cburmeister** [comment]
It's not abandoned... but not actively maintained.

**Comment by jeffwidman** [comment]
Thanks!

**Comment by cburmeister** [comment]
@jeffwidman that's very exciting to hear! I wouldn't mind some help getting things smoothed out, more documentation, update and reduce dependencies in `requirements.txt`, PEP8, etc. There's never enough time in the day.

**Pull request merged**
